export const CART_ADD_ITEM = 'CART_ADD_ITEM';
export const CART_REMOVE_ITEM = 'CART_REMOVE_ITEM';
export const CART_GET_ITEM = 'CART_GET_ITEM';

export const CART_ADD_ITEM_FAIL = 'CART_ADD_ITEM_FAIL';
export const CART_REMOVE_ITEM_FAIL = 'CART_REMOVE_ITEM_FAIL';
export const CART_GET_ITEM_FAIL = 'CART_GET_ITEM_FAIL';

export const EMPTY_CART_ITEM = 'EMPTY_CART_ITEM';